# Generated by Django 5.0.7 on 2024-08-24 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='brand',
            new_name='owner',
        ),
    ]
